application: rhu-cssi
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /Styles
  static_dir: Styles
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /Scripts
  static_dir: Scripts

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
